export { default as HomeHero } from './hero'
export { default as HomePopularCourse } from './popular-courses'
export { default as HomeFeature } from './feature'
export { default as HomeTestimonial } from './testimonial'
export { default as HomeOurMentors } from './mentors'
export { default as HomeNewsLetter } from './newsletter'
export { default as HomeTrustAndProcess } from './trust-and-process'
export { default as HomeContactCta } from './contact-cta'
